### ISSUE TITLE
Feature Request: auto fill movies/tv metadata in yml file

### ISSUE THREAD

**Issue by ahatdude** [Kometa-Team/Kometa#672] opened 2022-01-30 03:18 UTC
**Is your feature request related to a problem? Please describe.**
This is not a problem, but it would definitely be a QoL feature. Filling in the movies.yml is quite a long process if you have a big library.

**Describe the solution you'd like**
In an ideal world PMM would retrieve all the metadata of all movies from plex regarding the category in question. For example, instead of having to fill in thousands of metadata lines for the movies category, PMM could retrieve all the metadata from plex (the database, but that is in SQL) in a particular category and autofill the yml with the relevant details. Ideally in a directory and filename of our choosing. This would save a lot of time, but not sure how feasible it is. Currently it's doable, but requires various individual steps and quite hard to automate. 
Cherry on top of the cake: finding a way to download posters from somewhere like ThePosterDatabase and then automatically changing the "file_poster" to the newly downloaded one. Maybe even being able to select favourite users to download from etc

**Describe alternatives you've considered**
I've considered creating a VM on unRAID and automating a few scripts: 
1) retrieve all metadata (a user on discord taught me how to use his jS script) 
2) merge all the individual yml files into one for each category (movies, tv etc)
3) Find a script to change the poster metadata to something that is preferred by me.

This is obviously a bit more complex and having it all "in the same place" (i.e. PMM) would be perfect.

I just thought of this, but does the cache file have that information? Could it be gotten from there - at the very least the titles?

I'd be happy to clarify anything if you're unsure of what I mean or any testing that could be necessary on my part.

**Comment by meisnate12** [comment] 2022-01-30 03:47
duplicate of #468 which was also just added to develop i haven't detailed how to use it yet but check the wiki after the next major release coming soon

**Closed as completed by meisnate12** 2022-01-30 03:47 UTC
Labels: duplicate, enhancement
