### ISSUE TITLE
[Bug]: SyntaxWarning

### ISSUE THREAD

**Issue by TechJedi51** [Kometa-Team/Kometa#821] opened 2022-04-12 17:59 UTC
### Version Number

1.16.3

### What branch are you on?

nightly

### Describe the Bug

Upon running with the command:

`docker run -it -v "/Users/pmm/plex-meta-manager:/config:rw" meisnate12/plex-meta-manager --run`

The Error below appears:

```
/modules/meta.py:994: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if season.seasonNumber is 0:

```
But PMM seems to run okay.

### Logs

https://gist.github.com/TechJedi51/a7b6fac5a8de9f7709c51881bde86a4a

**Comment by meisnate12** [comment] 2022-04-12 19:59
Dupe of #813

**Closed as completed** 2022-04-12 19:59 UTC
Labels: duplicate
