### ISSUE TITLE
Feature: Find Shows/Movies with Missing Data

### ISSUE THREAD

**Issue by efaden** [Kometa-Team/Kometa#385] opened 2021-09-10 00:03 UTC
I'd like to be able to find all shows and movies with missing metadata and force a refresh for the item.  For shoes an example would be where the Season name is Season #, or Episode #, etc.... Or for a show or movie where the summary is blank.

I'm not sure if it would be reasonable/easy to incorporate, but would be really nice.  Sometimes I grab a show before it has metadata.  Unless i refresh manually that show gets stuck with no summary, etc.

**Comment by meisnate12** [comment] 2021-09-13 03:29
duplicate of #294 i just havent gotten around to implementing this yet

**Closed as completed by meisnate12** 2021-09-13 03:29 UTC
Labels: duplicate
