### ISSUE TITLE
X-men trakt link is dead 

### ISSUE THREAD

**Issue by nemchik** [Kometa-Team/Kometa#2198] opened 2024-08-18 02:26 UTC
### Link to File

https://github.com/Kometa-Team/Kometa/blob/master/defaults%2Fplaylist.yml

### Version Number

2.0.2

### What branch are you on?

master

### Describe the Bug

The X-Men playlist from trakt seems to be missing (dead link) 

https://trakt.tv/users/heyitsbea/lists/x-men

It should probably be replaced or removed.

**Comment by antwanchild** [comment] 2024-08-18 02:43
This has been fixed in nightly

**Comment by YozoraXCII** [comment] 2024-08-18 09:09
Closing as duplicate of #2150

**Closed as completed by YozoraXCII** 2024-08-18 09:09 UTC
