### ISSUE TITLE
Bug: Library operation crash: 'Track' object has no attribute 'sortTitle'

### ISSUE THREAD

**Issue by palla89** [Kometa-Team/Kometa#744] opened 2022-03-03 13:49 UTC
**Describe the Bug**
When I run on latest develop version the library operation "Update Blank Track Titles: True" after PMM loads all the music tracks, it stops with error:

<img width="709" alt="Schermata 2022-03-03 alle 14 40 33" src="https://user-images.githubusercontent.com/12301205/156576068-4251acec-f2fe-4cb2-8422-4cea76ea0b61.png">

**Relevant Collection Config**

  ```
Musica:
    operations:
      update_blank_track_titles: true
```

**Plex Meta Manager Info**
Version: 1.15.1-develop85

**Link to logs (required)**
[https://gist.github.com/palla89/496e6f4518f418bfe4d83555b044e702](https://gist.github.com/palla89/496e6f4518f418bfe4d83555b044e702)

**Comment by meisnate12** [comment] 2022-03-03 15:05
ok so ultimately the issue is with the metadata of the item ive tried to add a way to refresh the metadata hopefully that works if not you have to plex dance the item

**Comment by palla89** [comment] 2022-03-03 15:37
Hi! Thank you for your fast fix!! Unfortunately it doesn't work xD I think it could be because reading from your commit, you check the key 'titleSort' instead of 'sortTitle'?

**Comment by YozoraXCII** [comment] 2022-03-03 15:40
> Hi! Thank you for your fast fix!! Unfortunately it doesn't work xD I think it could be because reading from your commit, you check the key 'titleSort' instead of 'sortTitle'?

titleSort is the name of the field if you look within the XML file of the songs, it is just named "Sort Title" within the UI, but the underlying code is titleSort

**Comment by palla89** [comment] 2022-03-03 15:43
Ops! Thank you!! 
I don't understand why but it still crashes unfortunately, with the same error. Version is: Version: 1.15.1-develop88 so it should be the correct one... But nothing changed:

<img width="716" alt="Schermata 2022-03-03 alle 16 43 11" src="https://user-images.githubusercontent.com/12301205/156599041-8c85bb46-a54c-41e5-a240-c1308147c08f.png">

**Comment by YozoraXCII** [comment] 2022-03-03 15:45
> Ops! Thank you!! I don't understand why but it still crashes unfortunately, with the same error. Version is: Version: 1.15.1-develop88 so it should be the correct one... But nothing changed:
> 
> <img alt="Schermata 2022-03-03 alle 16 43 11" width="716" src="https://user-images.githubusercontent.com/12301205/156599041-8c85bb46-a54c-41e5-a240-c1308147c08f.png">

I've opened a thread on the Discord and tagged you in it, might be easier to discuss there

**Comment by meisnate12** [comment] 2022-03-03 15:49
yea that was my bad i used the wrong name should be fixed now

**Closed as completed** 2022-03-08 08:47 UTC
Labels: bug, status:added-to-develop
