### ISSUE TITLE
Plex_search: Genre: seems to be erroring out

### ISSUE THREAD

**Issue by SerinitySW** [Kometa-Team/Kometa#105] opened 2021-03-13 23:34 UTC
Using 1.4.0, the `genre:` builder seems to not be working - spitting out `Unknown Error: Unknown filter category: genre`. Snippet from logs here: https://pastebin.com/yuwPmLnd

Config:

```
    Adventure:
        plex_search:
            genre: 
                - Adventure
                - Action/Adventure
        trakt_list:
            - https://trakt.tv/users/retrogran/lists/adventure-movies?sort=title,asc
            - https://trakt.tv/users/niklcc/lists/action-adventure-movies
```

Also doesn't work with only one genre:

`genre: Adventure`

**Comment by meisnate12** [comment] 2021-03-13 23:38
duplicate of #78 it should be fixed once https://github.com/pkkid/python-plexapi/pull/693 pull request is added to the PlexAPI release until then its going to, unfortunately, remain broke unless you roll back the version of your PMS

**Closed as completed by meisnate12** 2021-03-13 23:38 UTC
Labels: duplicate
