### ISSUE TITLE
Feature Request: Build Libraries from tags

### ISSUE THREAD

**Issue by ponchohoncho** [Kometa-Team/Kometa#746] opened 2022-03-04 22:43 UTC
I'd like to build out separate libraries for things like 4K media or Kids, but I don't know that I want to move the media into separate folders.

Is it possible to do something like https://github.com/adamgot/python-plexlibrary does and instead of building Libraries from trakt lists, it builds libraries from tags (like genre, rating, or another custom tag) in the media?

**Comment by meisnate12** [comment] 2022-03-06 00:28
duplicate of #419

**Closed as completed by meisnate12** 2022-03-06 00:28 UTC
Labels: duplicate, enhancement
