### ISSUE TITLE
[Bug]: my anime list seasonal anime returning currently airing (not just seasonal). 

### ISSUE THREAD

**Issue by MattSidney** [Kometa-Team/Kometa#1153] opened 2022-11-03 22:01 UTC
### Version Number

na 

### What branch are you on?

master

### Describe the Bug

My Anime List _season pull all currently airing anime rather than just the seasonal anime which is presented here: https://myanimelist.net/anime/season

### Relevant Collection/Overlay/Playlist Definition

```yml
PMM/chart/myanimelist.yml
```

### Logs

na

**Comment by MattSidney** [comment] 2022-11-03 22:03
created a scrappy PR here: https://github.com/meisnate12/Plex-Meta-Manager/pull/1152

**Comment by meisnate12** [comment] 2022-11-08 03:26
this isnt actually a bug the list is showing the correct items you just want it filtered more im closing this as its a FR not a bug

**Closed as completed by meisnate12** 2022-11-08 03:26 UTC
Labels: bug, status:not-yet-viewed
